# Generated by Django 4.0.4 on 2022-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(blank=True, choices=[('AA', 'active_account'), ('RP', 'reset_password')], default='', max_length=20),
        ),
    ]
