# Generated by Django 4.0.4 on 2022-05-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='otp_type',
            new_name='blog_status',
        ),
    ]
