# Generated by Django 4.0.4 on 2022-05-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_comment', '0002_rename_comment_by_comment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_and_comment.post'),
        ),
    ]
